name: Test

on:
  pull_request:
  push:

jobs:
  test__package-lint__byte-compile__elisp-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 26.3
          - 27.2
        ignore_warnings:
          - true
        include:
          - emacs_version: snapshot
            ignore_warnings: false
    steps:
    - uses: actions/checkout@v3
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: package-install
      run: make package-install
    - name: lisp-test
      run: make lisp-test
    - name: package-lint
      run: make package-lint
    - name: byte-compile
      run: make byte-compile
    - name: elisp-lint
      run: make elisp-lint
